In [0]:
import numpy as np

In [0]:
# Setup for questions 1 and 2
arr1=np.arange(40).reshape(8,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [0]:
# Q1. From arr1 you have to fetch out every alternate column starting from col1
arr1[:, ::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24],
       [25, 27, 29],
       [30, 32, 34],
       [35, 37, 39]])

In [0]:
# Q2. From arr1 fetch an array which would contain {0,2,4} {15,17,19} and {30,32,34} 
arrx=arr1[::3,::2]
arrx

array([[ 0,  2,  4],
       [15, 17, 19],
       [30, 32, 34]])

In [0]:
# Setup for question

# Generating a random numpy array of intergers ranging between 1 and 100

arr2=np.random.randint(low=1, high=10000, size=10).reshape(2,5)
arr2

array([[5567, 6258, 9661, 7497, 3423],
       [6343, 3358, 5286, 8950, 1056]])

 **Normalization** rescales the values into a range of [0,1]. This might be useful in some cases where all parameters need to have the same positive scale. You have to do this a lot in machine learning for eg you are working with 2 cols, one is total runs scored by a batsman(in the scale of 1000s), and the second is number of matches played by him(in the scale of 10s). The formula for normalization is given below

 Xchanged=(X−Xmin)/(Xmax−Xmin)

In [0]:
# Q3. Write a code to normalize arr2.

In [0]:
np.percentile(arr1,25)

9.75

Missing values are a pain in the a**(sorry for language). But yes trust me.

In [0]:
# Q4. How would you check if your numpy array has valuessome missing ?

# Hint: Thoda research karo numpy me existing functions hai
arry = np.array([[3,5,np.nan,np.nan],[5,np.nan,3,5],[np.nan,np.nan,5,np.nan],[1,np.nan,3,4]])
np.isnan(arry)


array([[False, False,  True,  True],
       [False,  True, False, False],
       [ True,  True, False,  True],
       [False,  True, False, False]])

In [0]:
np.argwhere(np.isnan(arry))

array([[0, 2],
       [0, 3],
       [1, 1],
       [2, 0],
       [2, 1],
       [2, 3],
       [3, 1]])

In [0]:
# Q5. Write a function which will accept 2 arguments.
# First: A 1D numpy array arr
# Second: An integer n {Please make sure n<=len(arr)}

# Output: The output should be the nth largest item out of the array

# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40

In [0]:
def Nth(arr,n):
  arr.sort(reverse=True)
  print(arr[n-1])

In [0]:
arr1=[12,34,40,7,1,0]
Nth(arr1,3)


12


In [0]:
arr2=[12,34,40,7,1,0]
Nth(arr2,1)

40
